[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bond"
version = "0.1.0"
description = "An AI Agent with many personas"
authors = [{ name = "Niklas Lorenz", email = "niklaslorenz1999@gmail.com" }]
readme = "README.md"
requires-python = "==3.12.3"
dependencies = [
    "beautifulsoup4==4.14.3",
    "ddgs==9.11.4",
    "pydantic==2.12.5",
    "requests==2.32.5",
    "returns==0.26.0",
    "smolagents[toolbox]==1.24.0",
    "urllib3==2.6.3",
    "textual",
]

[project.urls]
"Homepage" = "https://github.com/niklaslorenz/bond"
"Bug Tracker" = "https://github.com/niklaslorenz/bond/issues"

[project.scripts]
ask = "bond.cli.ask:main"
followup = "bond.cli.followup:main"
chat = "bond.cli.chat:main"


[tool.setuptools.packages.find]
where = ["src"]
