from typing import Literal, Protocol

from textual.notifications import SeverityLevel

from bond.behaviours.behaviour_event import BehaviourEvent
from bond.behaviours.behaviour_signal import BehaviourSignal
from bond.conversation.conversation import Conversation
from bond.tui.event import TuiEvent
from bond.tui.widgets import ChatMessage, ToolResultBlock

TuiStatus = Literal["Idle", "Waiting", "Receiving", "Tool Call"]


class ITuiEvent(Protocol):
    def get_type(self) -> str: ...
    def is_cancelled(self) -> bool: ...
    def set_cancelled(self, cancelled: bool = True): ...


class ITuiApp(Protocol):
    def clear_input(self): ...
    def add_message(self, message: ChatMessage): ...
    def add_user_message(self, text: str) -> ChatMessage: ...
    def add_assistant_message(
        self, author: str, text: str | None, thinking: str | None, merge: bool
    ) -> ChatMessage: ...
    def add_system_message(self, author: str, text: str | None) -> ChatMessage: ...
    def add_tool_call(self, function_name: str, merge: bool) -> ToolResultBlock: ...
    def set_status(self, status: TuiStatus): ...
    def set_persona(self, persona_name: str): ...
    def stop(self): ...
    def open_confirmation_prompt(self, request: str): ...
    def clear_chat(self): ...
    def synchronize(self, conversation: Conversation): ...


class ITuiState(Protocol):
    def handle_tui_event(self, event: ITuiEvent): ...
    def handle_behaviour_event(self, event: BehaviourEvent): ...
    def on_enter(self, source: "ITuiState"): ...
    def on_exit(self, destination: "ITuiState"): ...


class ITuiStateMachine(Protocol):
    def handle_invalid_behaviour_event(self, event: BehaviourEvent): ...
    def handle_invalid_tui_event(self, event: ITuiEvent): ...
    def change_state(self, destination: "ITuiState"): ...
    def send_signal(self, signal: BehaviourSignal): ...
    def schedule_tui_event(self, event: TuiEvent, *, millis: int): ...
    def notify(self, message: str, severity: SeverityLevel = "information"): ...
    def get_app(self) -> ITuiApp: ...
    def stop(self): ...
