from typing import Protocol

from bond.conversation.types import ToolCall, UsageInfo
from bond.endpoints.chat_completions import CompletionChunk, CompletionResponse


class AgentOutputEnvironment(Protocol):
    def start_streaming_response(self, name: str | None): ...
    def end_streaming_response(self, usage: UsageInfo | None): ...
    def handle_response_chunk(self, chunk: CompletionChunk): ...

    def handle_response(self, response: CompletionResponse): ...
    def handle_tool_result(self, tool_call: ToolCall, tool_output: str): ...
